import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  corePlugins: { preflight: false },
  theme: {
    extend: {
      colors: {
        ink: {
          900: 'var(--ink-900)',
          850: 'var(--ink-850)',
          800: 'var(--ink-800)',
          700: 'var(--ink-700)',
        },
        accent: {
          yellow: 'var(--accent-yellow)',
          'yellow-deep': 'var(--accent-yellow-deep)',
          'yellow-mustard': 'var(--accent-yellow-mustard)',
        },
        team: {
          red: 'var(--team-red)',
          'red-soft': 'var(--team-red-soft)',
          'red-deep': 'var(--team-red-deep)',
          blue: 'var(--team-blue)',
          'blue-soft': 'var(--team-blue-soft)',
          'blue-deep': 'var(--team-blue-deep)',
          neutral: 'var(--team-neutral)',
        },
        magenta: {
          500: 'var(--magenta-500)',
          300: 'var(--magenta-300)',
          700: 'var(--magenta-700)',
        },
        fire: { red: 'var(--fire-red)', pink: 'var(--fire-pink)' },
        sky: { 300: 'var(--sky-300)' },
        cyan: { 400: 'var(--cyan-400)', 300: 'var(--cyan-300)', 200: 'var(--cyan-200)' },
        lime: {
          500: 'var(--lime-500)',
          400: 'var(--lime-400)',
          300: 'var(--lime-300)',
          700: 'var(--lime-700)',
          900: 'var(--lime-900)',
        },
        orange: { 500: 'var(--orange-500)' },
        peach: { 300: 'var(--peach-300)' },
        fg: {
          primary: 'var(--fg-primary)',
          secondary: 'var(--fg-secondary)',
          tertiary: 'var(--fg-tertiary)',
          muted: 'var(--fg-muted)',
          faint: 'var(--fg-faint)',
          softgray: 'var(--fg-softgray)',
          steel: 'var(--fg-steel)',
        },
        bg: {
          page: 'var(--bg-page)',
          elevated: 'var(--bg-elevated)',
          card: 'var(--bg-card)',
          'card-solid': 'var(--bg-card-solid)',
          overlay: 'var(--bg-overlay)',
        },
        border: {
          subtle: 'var(--border-subtle)',
          DEFAULT: 'var(--border-default)',
          strong: 'var(--border-strong)',
          accent: 'var(--border-accent)',
        },
      },
      fontFamily: {
        ui: ['var(--font-ui)'],
        display: ['var(--font-display)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs: 'var(--fs-xs)',
        sm: 'var(--fs-sm)',
        body: 'var(--fs-body)',
        'body-lg': 'var(--fs-body-lg)',
        base: 'var(--fs-base)',
        md: 'var(--fs-md)',
        lg: 'var(--fs-lg)',
        xl: 'var(--fs-xl)',
        '2xl': 'var(--fs-2xl)',
        '3xl': 'var(--fs-3xl)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        pill: 'var(--radius-pill)',
        full: 'var(--radius-full)',
      },
      spacing: {
        0: 'var(--sp-0)',
        1: 'var(--sp-1)',
        2: 'var(--sp-2)',
        3: 'var(--sp-3)',
        4: 'var(--sp-4)',
        5: 'var(--sp-5)',
        6: 'var(--sp-6)',
        8: 'var(--sp-8)',
        10: 'var(--sp-10)',
        12: 'var(--sp-12)',
        16: 'var(--sp-16)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        lift: 'var(--shadow-lift)',
      },
    },
  },
  plugins: [],
} satisfies Config;
