// tokens.d.ts — typed handle on token names declared in styles/tokens.css.
// Keep this in sync with the :root block in tokens.css.
// Contract: specs/003-design-handoff/contracts/tokens.contract.md

export type TokenName =
  // Brand — ink surface
  | '--ink-900'
  | '--ink-850'
  | '--ink-800'
  | '--ink-700'
  | '--ink-veil-93'
  | '--ink-veil-96'
  // Brand — accents
  | '--accent-yellow'
  | '--accent-yellow-deep'
  | '--accent-yellow-mustard'
  | '--accent-yellow-dim'
  | '--magenta-500'
  | '--magenta-300'
  | '--magenta-700'
  | '--magenta-soft'
  | '--fire-red'
  | '--fire-pink'
  | '--sky-300'
  | '--sky-glow'
  | '--cyan-400'
  | '--cyan-300'
  | '--cyan-200'
  | '--lime-500'
  | '--lime-400'
  | '--lime-300'
  | '--lime-700'
  | '--lime-900'
  | '--orange-500'
  | '--peach-300'
  // Text neutrals
  | '--fg-primary'
  | '--fg-secondary'
  | '--fg-tertiary'
  | '--fg-muted'
  | '--fg-faint'
  | '--fg-softgray'
  | '--fg-steel'
  // Team / cell state
  | '--team-red'
  | '--team-red-soft'
  | '--team-red-deep'
  | '--team-blue'
  | '--team-blue-soft'
  | '--team-blue-deep'
  | '--team-neutral'
  | '--cell-empty'
  | '--cell-empty-border'
  | '--cell-hover'
  | '--cell-hover-border'
  | '--cell-own'
  | '--cell-opponent'
  | '--cell-disabled'
  // Semantic
  | '--bg-page'
  | '--bg-elevated'
  | '--bg-card'
  | '--bg-card-solid'
  | '--bg-overlay'
  | '--border-subtle'
  | '--border-default'
  | '--border-strong'
  | '--border-accent'
  | '--focus-ring'
  // Gradients
  | '--grad-fire'
  | '--grad-magenta-glass'
  | '--grad-magenta-solid'
  | '--grad-lime'
  | '--grad-page-veil'
  // Glows / shadows
  | '--glow-sky'
  | '--glow-yellow'
  | '--glow-magenta'
  | '--glow-red'
  | '--shadow-card'
  | '--shadow-lift'
  // Radii
  | '--radius-xs'
  | '--radius-sm'
  | '--radius-md'
  | '--radius-lg'
  | '--radius-xl'
  | '--radius-2xl'
  | '--radius-3xl'
  | '--radius-pill'
  | '--radius-full'
  // Spacing
  | '--sp-0'
  | '--sp-1'
  | '--sp-2'
  | '--sp-3'
  | '--sp-4'
  | '--sp-5'
  | '--sp-6'
  | '--sp-8'
  | '--sp-10'
  | '--sp-12'
  | '--sp-16'
  // Typography
  | '--font-ui'
  | '--font-display'
  | '--font-mono'
  | '--fw-regular'
  | '--fw-medium'
  | '--fw-semibold'
  | '--fw-bold'
  | '--fs-xs'
  | '--fs-sm'
  | '--fs-body'
  | '--fs-body-lg'
  | '--fs-base'
  | '--fs-md'
  | '--fs-lg'
  | '--fs-xl'
  | '--fs-2xl'
  | '--fs-3xl'
  | '--lh-tight'
  | '--lh-snug'
  | '--lh-normal'
  | '--lh-loose'
  // Motion
  | '--ease-out'
  | '--ease-in-out'
  | '--dur-fast'
  | '--dur-base'
  | '--dur-slow'
  // Breakpoints
  | '--bp-mobile'
  | '--bp-tablet'
  | '--bp-desktop'
  | '--bp-wide'
  // Blur
  | '--blur-sm'
  | '--blur-md'
  | '--blur-lg';

/** Returns `var(--token-name)` with the TokenName narrowed at the type level. */
export function cssVar<T extends TokenName>(name: T): `var(${T})` {
  return `var(${name})` as `var(${T})`;
}
